<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- If page name is not defined, use a default one -->
    <title><?php echo isset($page_name) ? $page_name : 'UM-SJTU JI LIFE'; ?></title>

    <link rel="shortcut icon" href="<?php echo ROOT_DIR; ?>/img/favicon.png">
    <link rel="stylesheet" href="<?php echo ROOT_DIR; ?>/node_modules/weui/dist/style/weui.min.css">
</head>

<body>

<div class="weui-search-bar" id="career-search-bar">
    <form class="weui-search-bar__form">
        <div class="weui-search-bar__box">
            <i class="weui-icon-search"></i>
            <input type="search" class="weui-search-bar__input" id="career-search-input" placeholder="搜索" required/>
            <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
        </div>
        <label class="weui-search-bar__label" id="searchText">
            <i class="weui-icon-search"></i>
            <span>搜索</span>
        </label>
    </form>
    <a href="javascript:" class="weui-search-bar__cancel-btn" id="career-search-cancel">取消</a>
</div>

<div class="weui-tab" id="career-tab">
    <div class="weui-navbar" id="career-navbar">
        <!-- Generated by template -->
    </div>
    <div class="weui-tab__panel" id="career-panel">
        <div class="weui-panel__bd" id="career-list">
            <!-- Generated by template -->
        </div>
        <div class="weui-panel__ft" id="career-panel-footer">
            <a href="javascript:void(0);" class="weui-cell weui-cell_access weui-cell_link" id="career-panel-more-btn">
                <div class="weui-cell__bd" id="career-panel-more-text"></div>
                <span class="weui-cell__ft"></span>
            </a>
        </div>
    </div>
</div>


<!--<div class="weui-cells searchbar-result" id="searchResult">
    <div class="weui-cell weui-cell_access">
        <div class="weui-cell__bd weui-cell_primary">
            <p>实时搜索文本</p>
        </div>
    </div>
    <div class="weui-cell weui-cell_access">
        <div class="weui-cell__bd weui-cell_primary">
            <p>实时搜索文本</p>
        </div>
    </div>
    <div class="weui-cell weui-cell_access">
        <div class="weui-cell__bd weui-cell_primary">
            <p>实时搜索文本</p>
        </div>
    </div>
    <div class="weui-cell weui-cell_access">
        <div class="weui-cell__bd weui-cell_primary">
            <p>实时搜索文本</p>
        </div>
    </div>
</div>-->

<script id="navbar-template" type="text/x-handlebars-template">
    {{#each this}}
    <div class="weui-navbar__item">
        {{name}}
    </div>
    {{/each}}
</script>

<script id="list-template" type="text/x-handlebars-template">
    {{#each this}}
    <a href="{{#if url}}{{{url}}}{{else}}javascript:void(0);{{/if}}" class="weui-media-box weui-media-box_appmsg">
        <div class="weui-media-box__hd">
            <img class="weui-media-box__thumb"
                 {{#if img}}
                 src="{{{img}}}"
                 {{else}}
                 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAAB4CAMAAAAOusbgAAAAeFBMVEUAwAD///+U5ZTc9twOww7G8MYwzDCH4YcfyR9x23Hw+/DY9dhm2WZG0kbT9NP0/PTL8sux7LFe115T1VM+zz7i+OIXxhes6qxr2mvA8MCe6J6M4oz6/frr+us5zjn2/fa67rqB4IF13XWn6ad83nxa1loqyirn+eccHxx4AAAC/klEQVRo3u2W2ZKiQBBF8wpCNSCyLwri7v//4bRIFVXoTBBB+DAReV5sG6lTXDITiGEYhmEYhmEYhmEYhmEY5v9i5fsZGRx9PyGDne8f6K9cfd+mKXe1yNG/0CcqYE86AkBMBh66f20deBc7wA/1WFiTwvSEpBMA2JJOBsSLxe/4QEEaJRrASP8EVF8Q74GbmevKg0saa0B8QbwBdjRyADYxIhqxAZ++IKYtciPXLQVG+imw+oo4Bu56rjEJ4GYsvPmKOAB+xlz7L5aevqUXuePWVhvWJ4eWiwUQ67mK51qPj4dFDMlRLBZTqF3SDvmr4BwtkECu5gHWPkmDfQh02WLxXuvbvC8ku8F57GsI5e0CmUwLz1kq3kD17R1In5816rGvQ5VMk5FEtIiWislTffuDpl/k/PzscdQsv8r9qWq4LRWX6tQYtTxvI3XyrwdyQxChXioOngH3dLgOFjk0all56XRi/wDFQrGQU3Os5t0wJu1GNtNKHdPqYaGYQuRDfbfDf26AGLYSyGS3ZAK4S8XuoAlxGSdYMKwqZKM9XJMtyqXi7HX/CiAZS6d8bSVUz5J36mEMFDTlAFQzxOT1dzLRljjB6+++ejFqka+mXIe6F59mw22OuOw1F4T6lg/9VjL1rLDoI9Xzl1MSYDNHnPQnt3D1EE7PrXjye/3pVpr1Z45hMUdcACc5NVQI0bOdS1WA0wuz73e7/5TNqBPhQXPEFGJNV2zNqWI7QKBd2Gn6AiBko02zuAOXeWIXjV0jNqdKegaE/kJQ6Bfs4aju04lMLkA2T5wBSYPKDGF3RKhFYEa6A1L1LG2yacmsaZ6YPOSAMKNsO+N5dNTfkc5Aqe26uxHpx7ZirvgCwJpWq/lmX1hA7LyabQ34tt5RiJKXSwQ+0KU0V5xg+hZrd4Bn1n4EID+WkQdgLfRNtvil9SPfwy+WQ7PFBWQz6dGWZBLkeJFXZGCfLUjCgGgqXo5TuSu3cugdcTv/HjqnBTEMwzAMwzAMwzAMwzAMw/zf/AFbXiOA6frlMAAAAABJRU5ErkJggg=="
                 {{/if}}
            alt="">
        </div>
        <div class="weui-media-box__bd">
            <h4 class="weui-media-box__title">{{title}}</h4>
            <p class="weui-media-box__desc">{{abstract}}</p>
        </div>
    </a>
    {{/each}}
</script>


<script src="<?php echo ROOT_DIR; ?>/node_modules/jquery/dist/jquery.min.js"></script>
<script src="<?php echo ROOT_DIR; ?>/node_modules/weui.js/dist/weui.min.js"></script>
<script src="<?php echo ROOT_DIR; ?>/node_modules/handlebars/dist/handlebars.min.js"></script>

<script type="text/javascript">
    // 初始化
    var navbar_template = Handlebars.compile($("#navbar-template").html());
    var list_template = Handlebars.compile($("#list-template").html());
    var category_list = <?php echo json_encode($category);?>;
    var current_category_index;
    var current_keyword = '';
    var search_flag = false;
    var current_page;
    var global_timestamp;
    var per_page = 10;

    function ajax_data(category_id, keyword, callback) {
        var timestamp = global_timestamp = new Date();
        $.ajax({
            url: '<?php echo ROOT_DIR; ?>/career/wechat_list_data',
            type: 'GET',
            data: {
                category: category_id,
                keyword: keyword,
                page: current_page,
                per_page: per_page
            },
            dataType: 'json',
            success: function (data) {
                if (global_timestamp !== timestamp)return;
                callback(data);
            },
            error: function (data) {
                if (global_timestamp !== timestamp)return;
                data = [
                    {title: "title 1", abstract: "dsfhkujfdsbfdk", img: "111"},
                    {title: "title 2", abstract: "fdsbhkfdjbnfd", url: "http://www.baidu.com"},
                    {title: "title 3", abstract: "rhuigbkgf"},
                    {title: "title 4", abstract: "rhuoigbgfoij"},
                    {title: "title 5", abstract: "dsfhkujfdsbfdk"},
                    {title: "title 6", abstract: "fdsbhkfdjbnfd"},
                    {title: "title 7", abstract: "rhuigbkgf"},
                    {title: "title 8", abstract: "rhuoigbgfoij"},
                    {title: "title 9", abstract: "dsfhkujfdsbfdk"},
                    {title: "title 10", abstract: "fdsbhkfdjbnfd"}
                ];
                callback(data);
            }
        });
    }

    function search(keyword) {
        $("#career-navbar").hide();
        search_flag = true;
        current_keyword = keyword;
        current_page = 1;
        $("#career-list").html('');
        load_more();
    }

    // 切换类别时初始化列表
    function init_category(index) {
        $("#career-navbar").show();
        search_flag = false;
        current_category_index = index;
        current_page = 1;
        $("#career-list").html('');
        load_more();
    }

    function load_more() {
        var callback = function (data) {
            if (data.length > 0) {
                $("#career-list").append(list_template(data));
                $("#career-panel-more-text").html('查看更多');
                current_page++;
            } else {
                $("#career-panel-more-text").html('没有更多了');
            }
        };
        if (search_flag) {
            ajax_data(null, current_keyword, callback);
        } else {
            var category = category_list[current_category_index];
            ajax_data(category.id, null, callback);
        }
    }


    // 初始化搜索
    weui.searchBar('#career-search-bar');

    // 初始化导航栏
    $("#career-navbar").html(navbar_template(category_list));
    weui.tab('#career-tab', {
        defaultIndex: 0,
        onChange: function (index) {
            init_category(index);
        }
    });
    init_category(0);


    $("#career-panel-more-btn").on('click', function () {
        load_more();
    });

    $("#career-search-input").on('keyup', function () {
        var keyword = $("#career-search-input").val();
        if (keyword === current_keyword)return;
        current_keyword = keyword;
        if (!keyword) {
            init_category(current_category_index);
        } else {
            search(keyword);
        }
    });

    $("#career-search-cancel").on('click', function () {
        current_keyword = '';
        init_category(current_category_index);
    });


</script>


</body>
</html>